from __future__ import annotations

import json
import platform
import sys
from dataclasses import dataclass
from typing import Any

import numpy
import pandas
import sklearn

from ml_workbench.services.workspace import Workspace, utc_now
from ml_workbench.state import ProjectState

REPORT_FILE = "report.html"
SCRIPT_FILE = "reproduce.py"
MANIFEST_FILE = "manifest.json"


@dataclass(frozen=True)
class ReportResult:
    report: str
    script: str
    manifest: str


def render_script(state: ProjectState, workspace: Workspace) -> str:
    """EXPORT-01: emit a reproducible script from the step log and run metadata."""
    meta = _active_meta(state, workspace)
    task = dict(meta.get("task", {}) or {})
    data_hash = str(meta.get("data_hash", ""))
    seed = int(meta.get("seed", state.seed or 42))
    params = dict(meta.get("params", {}) or {})
    run_id = state.active_model_id or "run_00000000"
    model_id = str(meta.get("model_id", ""))

    steps = workspace.read_steps()
    cleaning = [entry for entry in steps if entry.tab == "cleaning"]
    encode_step = next(
        (
            entry
            for entry in reversed(steps)
            if entry.tab == "preprocessing" and entry.op == "encode"
        ),
        None,
    )
    scale_step = next(
        (
            entry
            for entry in reversed(steps)
            if entry.tab == "preprocessing" and entry.op == "scale"
        ),
        None,
    )
    transform_step = next(
        (
            entry
            for entry in reversed(steps)
            if entry.tab == "preprocessing" and entry.op == "target_transform"
        ),
        None,
    )
    split_step = next(
        (entry for entry in steps if entry.tab == "preprocessing" and entry.op == "split"), None
    )

    scaler = scale_step.params.get("scaler") if scale_step else None
    encoder = encode_step.params.get("encoder", "ordinal") if encode_step else "ordinal"
    transform = transform_step.params.get("transform") if transform_step else None
    test_size = split_step.params.get("test_size", 0.2) if split_step else 0.2

    lines = [
        '"""Reproducible script generated by ML Workbench (EXPORT-01).',
        "Rebuilds the exact cleaned dataset, preprocessing split and trained model",
        "from the raw data. It runs in a throwaway clone so the working project is",
        "never modified.",
        '"""',
        "from __future__ import annotations",
        "",
        "import shutil",
        "from pathlib import Path",
        "",
        "import numpy as np",
        "",
        "from ml_workbench.state import ProjectState, StepEntry",
        "from ml_workbench.services.workspace import Workspace, DatasetInfo, hash_file",
        "from ml_workbench.services.data_service import insert_dataset",
        "from ml_workbench.rules.task import build_task",
        "from ml_workbench.rules.cleaning import (",
        "    apply_imputation,",
        "    apply_outlier_treatment,",
        "    drop_missing_target,",
        "    fix_dtypes,",
        "    remove_duplicates,",
        ")",
        "from ml_workbench.services.preprocessing_service import (",
        "    PreprocessingOptions,",
        "    run_preprocessing,",
        ")",
        "from ml_workbench.services.training_service import train_model",
        "",
        f"PROJECT_ID = {state.project_id!r}",
        f"WORKSPACE_ROOT = Path({workspace.root.as_posix()!r})",
        f"SEED = {seed}",
        f"DATA_HASH = {data_hash!r}",
        "",
        "# Work in a throwaway clone so the working project is untouched.",
        f'CLONE_ROOT = WORKSPACE_ROOT.parent / f"reproduce-{data_hash[-16:]}"',
        "shutil.copytree(",
        "    WORKSPACE_ROOT / 'projects' / PROJECT_ID,",
        "    CLONE_ROOT / 'projects' / PROJECT_ID,",
        "    dirs_exist_ok=True,",
        ")",
        "",
        "ws = Workspace(project_id=PROJECT_ID, root=CLONE_ROOT)",
        "state = ProjectState(project_id=PROJECT_ID, seed=SEED)",
        "",
        "# 1. raw data (original uploaded version) and task definition",
        "frame = ws.read_version(ws.list_versions()[0])",
        "insert_dataset(state, ws, frame, source='reproduce-script')",
        f"state.task = build_task(frame, {task.get('learning_type', 'supervised')!r}, "
        f"target={task.get('target')!r}, task_type={task.get('task_type')!r})",
        "frame = state.frame",
        "",
        "# 2. cleaning replay in recorded order",
    ]

    for entry in cleaning:
        if entry.op == "dedupe":
            lines.append("frame, _ = remove_duplicates(frame)")
        elif entry.op == "fix_dtypes":
            lines.append("frame, _, _ = fix_dtypes(frame)")
        elif entry.op == "drop_rows":
            lines.append("frame = drop_missing_target(frame, state.task.target)")
        elif entry.op == "impute":
            columns = _py_repr(entry.params.get("columns"))
            strategy = entry.params.get("strategy")
            if strategy == "constant":
                lines.append(
                    f"frame = apply_imputation(frame, {columns}, 'constant', "
                    f"target=state.task.target, fill_value={_py_repr(entry.params.get('value'))})"
                )
            else:
                lines.append(
                    f"frame = apply_imputation(frame, {columns}, {strategy!r}, "
                    f"target=state.task.target)"
                )
        elif entry.op == "outlier_treatment":
            lines.append(
                f"frame = apply_outlier_treatment(frame, {_py_repr(entry.params.get('columns'))}, "
                f"{_py_repr(entry.params.get('op'))}, factor={entry.params.get('factor') or 1.5})"
            )
        else:
            continue

    base_id = max((entry.id for entry in steps), default=0)
    replayed_steps = []
    for index, entry in enumerate(cleaning):
        replayed_steps.append(
            f"    StepEntry(id={base_id + 1 + index}, tab='cleaning', op='replay', "
            f"params={_py_repr({'original_op': entry.op, 'params': entry.params})}, "
            f"dataset_hash_before='', dataset_hash_after='', created_at=''),"
        )
    lines += [
        "state.frame = frame",
        "",
        "# Mark cleaning as replayed so downstream gating treats it as done.",
        "state.steps = ws.read_steps() + [",
    ]
    lines += replayed_steps
    lines += [
        "    ]",
        "ws.write_steps(state.steps)",
        "",
        "# 3. persist the reproduced cleaned frame and verify the data hash",
        "version = ws.write_version(state.frame)",
        "state.dataset = DatasetInfo(",
        "    version=version.version,",
        "    path=str(version.path),",
        "    data_hash=version.data_hash,",
        "    row_count=version.row_count,",
        "    loaded_at=version.loaded_at,",
        ")",
        "assert state.dataset.data_hash == DATA_HASH, (",
        "    'replayed cleaning diverged', state.dataset.data_hash, DATA_HASH)",
        "",
        "# 4. preprocessing with the recorded choices (same split because seed matches)",
        "run_preprocessing(state, ws, PreprocessingOptions(",
        f"    scaler={_py_repr(scaler)}, encoder={_py_repr(encoder)}, "
        f"target_transform={_py_repr(transform)}, test_size={test_size!r}, seed={{SEED}}))",
        "",
        "# 5. train the same model with the recorded hyperparameters",
        f"result = train_model(state, ws, {model_id!r}, {_py_repr(params)}, "
        f"run_id={run_id!r}, mode='reproduce', seed={{SEED}})",
        "",
        "print(",
        "    'Replay OK:', result.run_id, result.model_id,",
        "    f'{result.primary}={result.mean:.4f}',",
        "    f'at {state.dataset.data_hash}',",
        ")",
        "",
    ]
    return "\n".join(lines)


def build_report(
    state: ProjectState,
    workspace: Workspace,
    run_id: str,
    outcome_files: tuple[str, ...],
    *,
    threshold: float = 0.5,
) -> ReportResult:
    """EXPORT-01: write the report, reproducible script and manifest into reports/."""
    workspace.ensure()
    meta = workspace.read_run_json(run_id, "meta.json")
    metrics = workspace.read_run_json(run_id, "metrics.json")
    data_hash = str(meta.get("data_hash", state.dataset.data_hash if state.dataset else ""))
    seed = int(meta.get("seed", state.seed or 42))
    steps = workspace.read_steps()

    script = render_script(state, workspace)
    script_path = workspace.reports_dir / SCRIPT_FILE
    script_path.write_text(script + "\n")

    manifest = {
        "project_id": state.project_id,
        "data_hash": data_hash,
        "seed": seed,
        "python": sys.version.split()[0],
        "platform": platform.system().lower(),
        "library_versions": {
            "sklearn": sklearn.__version__,
            "pandas": pandas.__version__,
            "numpy": numpy.__version__,
        },
        "steps": [{"tab": entry.tab, "op": entry.op} for entry in steps],
        "outcome_files": list(outcome_files),
        "threshold": threshold,
        "model": {
            "id": str(metrics.get("model_id", "")),
            "primary": str(metrics.get("primary", "")),
            "mean": metrics.get("mean"),
        },
        "created_at": utc_now(),
    }
    manifest_path = workspace.reports_dir / MANIFEST_FILE
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")

    html = _render_html(state, workspace, run_id, meta, metrics, outcome_files, threshold)
    report_path = workspace.reports_dir / REPORT_FILE
    report_path.write_text(html)

    return ReportResult(
        report=report_path.relative_to(workspace.project_dir).as_posix(),
        script=script_path.relative_to(workspace.project_dir).as_posix(),
        manifest=manifest_path.relative_to(workspace.project_dir).as_posix(),
    )


def _active_meta(state: ProjectState, workspace: Workspace) -> dict[str, Any]:
    run_id = state.active_model_id
    if run_id is None and state.models:
        run_id = state.models[-1].run_id
    if run_id is None:
        return {}
    return workspace.read_run_json(run_id, "meta.json")


def _render_html(
    state: ProjectState,
    workspace: Workspace,
    run_id: str,
    meta: dict[str, Any],
    metrics: dict[str, Any],
    outcome_files: tuple[str, ...],
    threshold: float,
) -> str:
    del workspace
    model_id = str(metrics.get("model_id", ""))
    primary = str(metrics.get("primary", ""))
    mean = metrics.get("mean")
    std = metrics.get("std")
    task_type = str(metrics.get("task_type", ""))
    files = "\n".join(f"<li><code>{name}</code></li>" for name in outcome_files)
    return f"""<!doctype html>
<html>
<head><meta charset="utf-8"><title>Model report — {model_id}</title></head>
<body>
<h1>Model report</h1>
<table>
<tr><th>project</th><td>{state.project_id}</td></tr>
<tr><th>run</th><td>{run_id}</td></tr>
<tr><th>model</th><td>{model_id}</td></tr>
<tr><th>task</th><td>{task_type}</td></tr>
<tr><th>primary metric</th><td>{primary}</td></tr>
<tr><th>mean</th><td>{mean if mean is None else f"{mean:.4f}"}</td></tr>
<tr><th>std</th><td>{std if std is None else f"{std:.4f}"}</td></tr>
<tr><th>target</th><td>{meta.get("task", {}).get("target", "")}</td></tr>
<tr><th>threshold</th><td>{threshold}</td></tr>
<tr><th>data hash</th><td><code>{meta.get("data_hash", "")}</code></td></tr>
<tr><th>seed</th><td>{meta.get("seed")}</td></tr>
</table>
<h2>Deliverables</h2>
<ul>{files}</ul>
<h2>Reproducibility</h2>
<p>{SCRIPT_FILE} rebuilds this exact pipeline from the raw data; {MANIFEST_FILE} pins
data hash, random seed and library versions.</p>
</body>
</html>
"""


def _py_repr(value: Any) -> str:
    return repr(value)
