"""Generate or refresh rule stub tests from docs/rules.md (merge-safe)."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
RULES_DOC = REPO_ROOT / "docs" / "rules.md"
OUTPUT_DIR = REPO_ROOT / "tests" / "rules"

SECTION_RE = re.compile(r"^## \d+\. (.+)$", re.M)
ROW_RE = re.compile(r"^\|\s*([A-Z]+-[0-9]+[a-c]?)(?:\s*⚠)?\s*\|(.*)\|\s*$", re.M)
TEST_NAME_RE = re.compile(r"`(test_\w+)`")

SECTION_FILES = {
    "Gating and navigation": "test_gating.py",
    "Staleness and state": "test_staleness.py",
    "Task and split selection": "test_task_and_split.py",
    "Cleaning": "test_cleaning.py",
    "Encoding, scaling, features, target transforms": "test_encoding_scaling_features.py",
    "Model selection and hyperparameters": "test_modelling.py",
    "Training and validation": "test_training.py",
    "Metrics": "test_metrics.py",
    "Prediction": "test_prediction.py",
    "Error analysis": "test_error_analysis.py",
    "Explainability": "test_explainability.py",
    "EDA": "test_eda.py",
    "Outcome and export": "test_outcome_export.py",
    "Warnings and unsupported combinations": "test_warnings.py",
    "Hints": "test_hints.py",
    "Performance": "test_performance.py",
}


def section_title(raw: str) -> str:
    return re.sub(r"\s*\(§[^)]*\)", "", raw.strip())


def parse_rules(doc_text: str) -> list[tuple[str, str, str]]:
    sections = [(m.start(), section_title(m.group(1))) for m in SECTION_RE.finditer(doc_text)]
    sections.append((len(doc_text), ""))

    rules: list[tuple[str, str, str]] = []
    for index in range(len(sections) - 1):
        start, title = sections[index]
        end = sections[index + 1][0]
        chunk = doc_text[start:end]
        for match in ROW_RE.finditer(chunk):
            rule_id = match.group(1)
            name_match = TEST_NAME_RE.search(match.group(2))
            if name_match:
                rules.append((rule_id, name_match.group(1), title))
    return rules


def stub_function(rule_id: str, test_name: str) -> str:
    return (
        f'@pytest.mark.skip(reason="pending implementation: docs/rules.md {rule_id}")\n'
        f"def {test_name}() -> None:\n"
        f'    raise NotImplementedError("docs/rules.md {rule_id}")\n'
    )


def existing_names(path: Path) -> set[str]:
    if not path.exists():
        return set()
    return set(re.findall(r"^def (test_\w+)\(", path.read_text(), re.M))


def render_file(rules: list[tuple[str, str, str]], already: set[str]) -> str:
    parts = [
        "# Generated by scripts/scaffold_rule_tests.py; existing functions are preserved.\n",
        "import pytest\n",
    ]
    for rule_id, test_name, _title in rules:
        if test_name not in already:
            parts.append("\n\n" + stub_function(rule_id, test_name))
    return "".join(parts) + "\n"


def group_by_file(rules: list[tuple[str, str, str]]) -> dict[str, list[tuple[str, str, str]]]:
    grouped: dict[str, list[tuple[str, str, str]]] = {}
    for rule_id, test_name, title in rules:
        filename = SECTION_FILES.get(title)
        if filename is None:
            raise SystemExit(f"docs/rules.md: unmapped section '{title}' — update SECTION_FILES")
        grouped.setdefault(filename, []).append((rule_id, test_name, title))
    return grouped


def check(rules: list[tuple[str, str, str]]) -> int:
    missing: list[str] = []
    for filename, entries in group_by_file(rules).items():
        path = OUTPUT_DIR / filename
        names = existing_names(path)
        missing.extend(test_name for _rid, test_name, _t in entries if test_name not in names)
    if missing:
        print("Missing rule tests (run scripts/scaffold_rule_tests.py):")
        for name in sorted(missing):
            print(f"  {name}")
        return 1
    print(f"OK: all {len(rules)} rule tests are wired.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify tests exist without writing")
    args = parser.parse_args()

    rules = parse_rules(RULES_DOC.read_text())
    if not rules:
        print("docs/rules.md: no rules parsed", file=sys.stderr)
        return 1

    if args.check:
        return check(rules)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for filename, entries in group_by_file(rules).items():
        path = OUTPUT_DIR / filename
        names = existing_names(path)
        new_content = render_file(entries, names)
        added = sum(1 for _r, n, _t in entries if n not in names)
        if path.exists():
            if added:
                path.write_text(
                    path.read_text().rstrip("\n")
                    + "\n"
                    + new_content.split("import pytest\n", 1)[1]
                )
            print(f"{path.relative_to(REPO_ROOT)}: +{added} stub(s), {len(entries) - added} kept")
        else:
            path.write_text(new_content)
            print(f"{path.relative_to(REPO_ROOT)}: +{added} stub(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
